image: docker:latest

stages:
  - docs
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_IMAGE: ebispot/eqtl-sumstats-api
  CI_REGISTRY_DOCS_IMAGE: ebispot/eqtl-sumstats-docs

# generate the docs with sphinx
sphinxdocs:
  image: $CI_REGISTRY_IMAGE:latest
  stage: docs
  script:
   - mkdir /logs
   - make clean
   - make html
  artifacts:
    expire_in: '2 hrs'
    paths:
    - docs/build/html
  only:
   - eqtls
  
# always build an image tagged with the commit SHA from master
build:
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt docker.io
   - docker pull $CI_REGISTRY_IMAGE:latest
   - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
   - eqtls


build_docs:
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt docker.io
   - docker pull $CI_REGISTRY_DOCS_IMAGE:latest
   - docker build -f nginx/Dockerfile --cache-from $CI_REGISTRY_DOCS_IMAGE:latest -t $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA
  dependencies: 
    - sphinxdocs
  only:
   - eqtls
  


# if a tag is created create an images with the tag and a latest
build_release:
  variables:
    GIT_STRATEGY: none
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
   - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
   - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
   - docker push $CI_REGISTRY_IMAGE:latest
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
   - tags

build_docs_release:
  image: $CI_REGISTRY_IMAGE:latest
  variables:
    GIT_STRATEGY: none
  stage: docs
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
   - docker pull $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA
   - docker tag $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_DOCS_IMAGE:latest
   - docker tag $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_TAG
   - docker push $CI_REGISTRY_DOCS_IMAGE:latest
   - docker push $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_TAG
  only:
   - tags


deploy_fallback:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy
  script:
    - echo "Deploy to fallback server"
    - mkdir -p /root/.kube
    - echo ${FALLBACK_KUBECONF} | base64 -d > /root/.kube/config
    - helm init
    - helm delete --purge eqtl-sumstats || true
    - sleep 30
    - helm install --name eqtl-sumstats --set k8Namespace=eqtl,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.uid=$UID,image.gid=$GID,staticService.image.repository=$CI_REGISTRY_DOCS_IMAGE,staticService.image.tag=$CI_COMMIT_SHA,volume.data.nfsServer=$NFS_SERVER,volume.data.path=$NFS_PATH ./eqtlss/ --wait
  environment:
    name: fallback
  when: manual
  only:
    - tags


deploy_prod:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy
  script:
    - echo "Deploy to production server"
    - mkdir -p /root/.kube
    - echo ${PROD_KUBECONF} | base64 -d > /root/.kube/config
    - helm init
    - helm delete --purge eqtl-sumstats || true
    - sleep 30
    - helm install --name eqtl-sumstats --set k8Namespace=eqtl,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.uid=$UID,image.gid=$GID,staticService.image.repository=$CI_REGISTRY_DOCS_IMAGE,staticService.image.tag=$CI_COMMIT_SHA,volume.data.nfsServer=$NFS_SERVER,volume.data.path=$NFS_PATH,replicaCount=3 ./eqtlss/ --wait
  environment:
    name: production
  when: manual
  only:
    - tags



