image: docker:latest

stages:
  - docs
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_IMAGE: ebispot/sumstats
  CI_REGISTRY_DOCS_IMAGE: ebispot/sumstats-docs

# generate the docs with sphinx
sphinxdocs:
  image: $CI_REGISTRY_IMAGE:latest
  stage: docs
  script:
   - mkdir logs
   - make clean
   - make html
  artifacts:
    expire_in: '2 hrs'
    paths:
    - docs/build/html
  only:
   - master
   - dev


# always build an image tagged with the commit SHA from master
build:
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt docker.io
   - docker pull $CI_REGISTRY_IMAGE:latest
   - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
   - master
   - dev

build_docs:
  stage: build
  script:
   - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
   - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt docker.io
   - docker pull $CI_REGISTRY_DOCS_IMAGE:latest
   - docker build -f nginx/Dockerfile --cache-from $CI_REGISTRY_DOCS_IMAGE:latest -t $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_DOCS_IMAGE:$CI_COMMIT_SHA
  dependencies:
    - sphinxdocs
  only:
   - master
   - dev


deploy_staging:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy
  script:
    - echo "Deploy to staging"
    - mkdir -p /root/.kube
    - echo ${FALLBACK_KUBECONF} | base64 -d > /root/.kube/config
    - helm init --stable-repo-url https://charts.helm.sh/stable
    - helm delete --purge sumstats-search-api || true
    - helm install --name sumstats-search-api --set k8Namespace=dev-gwas,service.name=ss-seach-api-dev,staticService.name=ss-search-api-docs-dev,staticService.path=/ss-search-api-docs-dev,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA,image.uid=$UID,image.gid=$GID,staticService.image.repository=$CI_REGISTRY_DOCS_IMAGE,staticService.image.tag=$CI_COMMIT_SHA,volume.data.nfsServer=$NFS_SERVER,volume.data.path=$NFS_PATH,replicaCount=1 ./k8chart/ --wait
  environment:
    name: sandbox
  only:
    - master
    - dev

