language: python
python:
  - "3.6"
branches:
  only:
  - master
  - test-travis
notifications:
  email:
  - olgavrou@ebi.ac.uk
os: osx
before_install:
  - brew install hdf5
install:
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - pytest
