# Should dp a check for whether chromosome 23 is present in file
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
steps: ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15']
ss_file_pattern: ss_files/{ss_file}.tsv
remote_vcf_location: 'https://storage.googleapis.com/gnomad-public/release/2.0.2/vcf/genomes'
