#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
clear
echo ""

file=$1

echo -e "${GREEN}Select first 50 lines${NC}:"
echo "Will save the first 50 lines of the $file file into a new file called: first_50_$file"
echo ""
echo -e "${GREEN}Select first 50 lines of file${NC}:"
echo "Will ask you to provide a file name and will save the first 50 lines of that file into a new file called: first_50_<Name of the file you entered>"
echo ""
echo -e "${GREEN}Peek into file${NC}:"
echo "Will print on screen the header of the file and the first line of data"
echo ""
echo -e "${GREEN}List all files in dir${NC}:"
echo "Will list all files in the current directory"
echo ""
echo -e "${GREEN}Get all unconventional variant ids${NC}:"
echo "Will take all the variant ids that are not an RS id or look like: chr:bp or chr_bp, and save them in a file called: strange_variant_ids_$file"
echo ""
echo -e "${GREEN}Extract variant${NC}:"
echo "Will ask you to provide the variant if header."
echo "Will ask you to provide a list of comma separated prefixes of variant IDs to be ignored (if any)"
echo "Will extract the variant id information and save it into a file called: variant_$file"
echo -e "${GREEN}"
echo       "Extract chromosome"
echo       "Extract base pair location"
echo        "Extract effect"
echo       "Extract other"
echo       "Extract frequency"
echo       "Extract odds ratio"
echo       "Extract standard error"
echo       "Extract beta"
echo       "Extract p-value"
echo  -e     "Extract range${NC}"
echo "For each of the above it will ask you to provide the header of the data you want to extract"
echo "Then it will ask you if in the column that corresponds to that header, there is other information saved or not"
echo "For example you might have a column that has the chromosome and the base pair location like: chr1:12354, or chr1:12345_A_G"
echo "If so, it will ask you questions to try and extract, only the information needed for each data column"
echo "It will ask you if the data column also has a prefix that needs to be removed, for example if we have [chr1], the prefix is [chr] and needs to be removed"
echo "It will save the data in a file called: chr|bp|effect|other|freq|or|se|beta|pval|range_$file respectively"
echo ""
echo -e "${GREEN}Combine all info${NC}:"
echo "Will take all the columns that have been extracted and combine them in one single file called: loadable_$file"
echo "Will fill in missing columns with \"-1\""
echo ""
echo -e "${GREEN}Delete all intermediate files${NC}:"
echo "Deletes all files created using the \"Extract x\" scripts, i.e. deletes all the files with the extracted columns"
echo ""
echo -e "${GREEN}Delete specific file${NC}:"
echo "Asks you to give the name of a file and deletes it"
echo ""
echo -e "${GREEN}Quit${NC}:"
echo "Quits the application"
