apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: {{.Values.k8Namespace}}
spec:
  rules:
  - host:
    http:
      paths:
      - path: {{.Values.ingress.path}}
        backend:
          serviceName: {{.Values.service.name}}
          servicePort: {{.Values.service.port}}
          
