from sumstats.common_constants import *

TO_LOAD_DSET_HEADERS = TO_LOAD_DSET_HEADERS_DEFAULT.copy()

TO_STORE_DSETS = TO_STORE_DSETS_DEFAULT.copy()
TO_STORE_DSETS.remove(CHR_DSET)

TO_QUERY_DSETS = TO_STORE_DSETS_DEFAULT.copy()
TO_QUERY_DSETS.remove(CHR_DSET)

BLOCK_SIZE = 100000
